Repository Bauddhik-Geeks/Hacktoberfest-2021, pull requests merged in 2021-10, with the labels that each got.

#3 Changes made in ReadMe
  ReadMe.md
Labels: documentation

#5 feat: all contributors
  .all-contributorsrc
Labels: enhancement

#4 docs: remove inaccurate badges
  README.md
Labels: documentation, enhancement
